######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 3 23:24:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h torrentWidget.h torrentsListWidget.h
SOURCES += main.cpp mainwindow.cpp torrentWidget.cpp torrentsListWidget.cpp

mac {
  CONFIG -=app_bundle
  CONFIG += x86
}
